# Form implementation generated from reading ui file 'vtpanel.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

__author__ = 'gerardofn@virustotal.com'

from PySide6 import QtCore, QtGui, QtWidgets
from . import qt6logo


class Qt6Ui_panelUI(object):
    def setupUi(self, panelUI):
        panelUI.setObjectName("panelUI")
        panelUI.resize(600, 1051)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(panelUI.sizePolicy().hasHeightForWidth())
        panelUI.setSizePolicy(sizePolicy)
        panelUI.setMinimumSize(QtCore.QSize(400, 0))
        panelUI.setMaximumSize(QtCore.QSize(16777215, 16777215))
        panelUI.setAutoFillBackground(False)
        panelUI.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(panelUI)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(panelUI)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabBar::tab { \n"
"border: 2px;\n"
"height: 20px;\n"
"width: 100%;\n"
"color: white;\n"
"background-color: rgb(248, 248, 248);\n"
"} \n"
"\n"
"QTabWidget::pane  { \n"
"border-left: 1px solid rgb(35, 61, 255);\n"
"border-right: 1px solid rgb(35, 61, 255);\n"
"border-bottom: 1px solid rgb(35, 61, 255);\n"
"border-top: 1px solid rgb(35, 61, 255);\n"
"}\n"
"\n"
"QTabBar::tab:selected { \n"
"color: white;\n"
"min-width: 10em;\n"
"background-color: rgb(42, 45, 255);\n"
"border-left: 1px solid rgb(42, 45, 255);\n"
"border-right: 1px solid rgb(42, 45, 255);\n"
"border-top: 1px solid rgb(42, 45, 255);\n"
"border-bottom: 1px solid rgb(42, 45, 255);\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"color: black;\n"
"min-width: 10em;\n"
"background-color: rgb(248, 248, 248);\n"
"border-left: 1px solid gray;\n"
"border-right: 1px solid gray;\n"
"border-top: 1px solid gray;\n"
"}\n"
"\n"
"QTabBarWidget::tab-bar {\n"
"color: black;\n"
"background-color: rgb(248, 248, 248);\n"
"border-bottom: 1px solid  rgb(35, 61, 255);\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_codeinsight = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_codeinsight.sizePolicy().hasHeightForWidth())
        self.tab_codeinsight.setSizePolicy(sizePolicy)
        self.tab_codeinsight.setObjectName("tab_codeinsight")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_codeinsight)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.info = QtWidgets.QGroupBox(self.tab_codeinsight)
        self.info.setAutoFillBackground(False)
        self.info.setTitle("")
        self.info.setFlat(True)
        self.info.setObjectName("info")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.info)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.cb_faddress = QtWidgets.QComboBox(self.info)
        self.cb_faddress.setObjectName("cb_faddress")
        self.gridLayout.addWidget(self.cb_faddress, 0, 2, 1, 1)
        self.le_codetype = QtWidgets.QLineEdit(self.info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_codetype.sizePolicy().hasHeightForWidth())
        self.le_codetype.setSizePolicy(sizePolicy)
        self.le_codetype.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_codetype.setText("")
        self.le_codetype.setReadOnly(True)
        self.le_codetype.setPlaceholderText("")
        self.le_codetype.setObjectName("le_codetype")
        self.gridLayout.addWidget(self.le_codetype, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.info)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.info)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.info)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.le_fname = QtWidgets.QLineEdit(self.info)
        self.le_fname.setObjectName("le_fname")
        self.le_fname.setReadOnly(True)
        self.gridLayout.addWidget(self.le_fname, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.info)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.le_faddress = QtWidgets.QLineEdit(self.info)
        self.le_faddress.setObjectName("le_faddress")
        self.le_faddress.setReadOnly(True)
        self.gridLayout.addWidget(self.le_faddress, 1, 2, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.info)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_16.addWidget(self.label_15)
        self.horizontalLayout_10.addLayout(self.verticalLayout_16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_20.addWidget(self.info)
        self.summary = QtWidgets.QGroupBox(self.tab_codeinsight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summary.sizePolicy().hasHeightForWidth())
        self.summary.setSizePolicy(sizePolicy)
        self.summary.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setBold(True)
        self.summary.setFont(font)
        self.summary.setFlat(True)
        self.summary.setObjectName("summary")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.summary)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.te_ci_summary = QtWidgets.QTextEdit(self.summary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_ci_summary.sizePolicy().hasHeightForWidth())
        self.te_ci_summary.setSizePolicy(sizePolicy)
        self.te_ci_summary.setMinimumSize(QtCore.QSize(0, 60))
        self.te_ci_summary.setObjectName("te_ci_summary")
        self.verticalLayout_2.addWidget(self.te_ci_summary)
        self.verticalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout_20.addWidget(self.summary)
        self.description = QtWidgets.QGroupBox(self.tab_codeinsight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        self.description.setMinimumSize(QtCore.QSize(40, 12))
        font = QtGui.QFont()
        font.setBold(True)
        self.description.setFont(font)
        self.description.setFlat(True)
        self.description.setObjectName("description")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.description)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.te_ci_description = QtWidgets.QTextEdit(self.description)
        self.te_ci_description.setObjectName("te_ci_description")
        self.verticalLayout_3.addWidget(self.te_ci_description)
        self.verticalLayout_20.addWidget(self.description)
        self.evaluation_widgets = QtWidgets.QHBoxLayout()
        self.evaluation_widgets.setObjectName("evaluation_widgets")
        spacerItem1 = QtWidgets.QSpacerItem(363, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.evaluation_widgets.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.tab_codeinsight)
        self.label_3.setObjectName("label_3")
        self.evaluation_widgets.addWidget(self.label_3)
        self.pb_accept = QtWidgets.QPushButton(self.tab_codeinsight)
        self.pb_accept.setObjectName("pb_accept")
        self.evaluation_widgets.addWidget(self.pb_accept)
        self.pb_discard = QtWidgets.QPushButton(self.tab_codeinsight)
        self.pb_discard.setObjectName("pb_discard")
        self.evaluation_widgets.addWidget(self.pb_discard)
        self.pb_refresh = QtWidgets.QPushButton(self.tab_codeinsight)
        self.pb_refresh.setObjectName("pb_refresh")
        self.evaluation_widgets.addWidget(self.pb_refresh)
        self.verticalLayout_20.addLayout(self.evaluation_widgets)
        self.line = QtWidgets.QFrame(self.tab_codeinsight)
        font = QtGui.QFont()
        font.setWeight(QtGui.QFont.Weight.Normal)
        self.line.setFont(font)
        self.line.setStyleSheet("color: black;\n"
" ")
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_20.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pb_askCI = QtWidgets.QPushButton(self.tab_codeinsight)
        self.pb_askCI.setObjectName("pb_askCI")
        self.horizontalLayout_4.addWidget(self.pb_askCI)
        self.pb_go = QtWidgets.QPushButton(self.tab_codeinsight)
        self.pb_go.setObjectName("pb_go")
        self.horizontalLayout_4.addWidget(self.pb_go)
        self.pb_autocomment = QtWidgets.QPushButton(self.tab_codeinsight)
        self.pb_autocomment.setObjectName("pb_autocomment")
        self.horizontalLayout_4.addWidget(self.pb_autocomment)
        self.pb_load = QtWidgets.QPushButton(self.tab_codeinsight)
        self.pb_load.setObjectName("pb_load")
        self.horizontalLayout_4.addWidget(self.pb_load)
        self.pb_export = QtWidgets.QPushButton(self.tab_codeinsight)
        self.pb_export.setObjectName("pb_export")
        self.horizontalLayout_4.addWidget(self.pb_export)
        self.verticalLayout_20.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_codeinsight, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_11.addLayout(self.verticalLayout)

        self.retranslateUi(panelUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(panelUI)

    def retranslateUi(self, panelUI):
        _translate = QtCore.QCoreApplication.translate
        panelUI.setWindowTitle(_translate("panelUI", "VirusTotal"))
        self.info.setAccessibleName(_translate("panelUI", "General"))
        self.label_2.setText(_translate("panelUI", "Code type:"))
        self.label_8.setText(_translate("panelUI", "Function name"))
        self.label.setText(_translate("panelUI", "Analyzed functions"))
        self.label_4.setText(_translate("panelUI", "Function address"))
        self.label_15.setText(_translate("panelUI", "<html><head/><body><p><img src=\":/vtlogo/vt_logo.png\"/></p></body></html>"))
        self.summary.setTitle(_translate("panelUI", "Summary"))
        self.description.setTitle(_translate("panelUI", "Description"))
        self.label_3.setText(_translate("panelUI", "Evaluate analysis:"))
        self.pb_accept.setText(_translate("panelUI", "Accept"))
        self.pb_discard.setText(_translate("panelUI", "Discard"))
        self.pb_refresh.setText(_translate("panelUI", "Refresh"))
        self.pb_askCI.setText(_translate("panelUI", "Ask CI"))
        self.pb_go.setText(_translate("panelUI", "Go"))
        self.pb_autocomment.setText(_translate("panelUI", "Autocomment"))
        self.pb_load.setText(_translate("panelUI", "Load"))
        self.pb_export.setText(_translate("panelUI", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_codeinsight), _translate("panelUI", "Code Insight Notebook"))
